Roald/move opname and resource around
kolonialno/troncos pull request #20
Opened 2022-10-06 14:39 UTC by RmStorm

2022-10-06 14:48 UTC, gbbirkisson requested changes

2022-10-06 14:48 UTC, gbbirkisson commented on troncos/traces/decorate.py
> +        attributes["resource"] = resource
Attributes can be None. Just pass `resource` into `_trace_function` below and be done with it.

2022-10-06 14:48 UTC, gbbirkisson commented on troncos/traces/decorate.py
> +        attributes["resource"] = resource
Attributes can be None

2022-10-06 14:48 UTC, gbbirkisson commented on troncos/traces/decorate.py
> +            attributes["resource"] = resource
Attributes can be None. Just pass `resource` into `_trace_function` below and be done with it.

2022-10-06 14:48 UTC, gbbirkisson commented on troncos/traces/decorate.py
> +        attributes["resource"] = resource
Attributes can be None. Just pass `resource` into `_trace_function` below and be done with it.

2022-10-06 14:51 UTC, RmStorm commented on troncos/traces/decorate.py
> +    *,
to force attribute to be a named parameter :sweat_smile: Seemed like a good idea

2022-10-06 15:02 UTC, gbbirkisson commented on troncos/traces/decorate.py
> +    with trace_block("cool.block", "data!", attributes={"some": "attribute"}):
Now this makes total sense. You have an operation name that is acting on some resource :+1: 

How does this make sense on the `trace_function` decorator? Is `data!`, aka `resource` dynamic? 

Can you add a similar example to the decorator docs?

2022-10-07 08:39 UTC, RmStorm commented on troncos/traces/decorate.py
> +    *,
It's not possible for the ones that have `*args` but I will add it to the other ones.

2022-10-07 09:22 UTC, gbbirkisson commented on pyproject.toml
> +types-requests = "^2.28.11.2"
This should be a dev dependency, and it already is: https://github.com/kolonialno/troncos/blob/main/pyproject.toml#L37

2022-10-07 09:22 UTC, gbbirkisson commented on .flake8
> +ignore = B009,W503
What is the reason for these ignores? Is it bothering you in a lot of places?

2022-10-07 09:58 UTC, gbbirkisson commented on README.md
> +    print("... do an action to a  thing...")
```suggestion
    print("... do an action to a thing...")
```

2022-10-07 11:09 UTC, gbbirkisson approved these changes

2022-10-07 11:18 UTC, merged